function (dap_gtest_link_libraries target)
    list(REMOVE_AT ARGV 0)
    find_library(GTEST_LIBRARY libgtest.a REQUIRED)
    if (CMAKE_CXX_COMPILER_ID MATCHES GNU)
        find_package(Threads REQUIRED)
        target_link_libraries(${target} ${ARGV} Threads::Threads ${GTEST_LIBRARY})
    else ()
        target_link_libraries(${target} ${ARGV} ${GTEST_LIBRARY})
    endif ()
endfunction ()
